language: julia

julia:
  - 0.6
  - nightly

env:
  global:
    - APM_TEST_PACKAGES="ink language-julia"
    - ATOM_LINT_WITH_BUNDLED_NODE="true"

  matrix:
    - ""
    - ATOMJL=master

os:
  - linux

dist: trusty

matrix:
  include:
    # Sanity check for OS X
    - os: osx
      julia: 0.6
      env: ATOMJL=master
    # Sanity check for Atom Beta
    - os: linux
      julia: 0.6
      env: ATOM_CHANNEL=beta
  allow_failures:
    - julia: nightly
    - env: ATOM_CHANNEL=beta

script:
  - julia ci/packages.jl
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - bash build-package.sh

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6
    - fakeroot
    - git
    - libsecret-1-dev

notifications:
    email: false
